# Theme: Llama
# Author: Liam Newmarch

set -g status-style "bg=#111111,fg=#f2f2f2"
set -g status-justify centre
set -g status-left-length 40
set -g status-right-length 60

set -g status-left "#[fg=#000000,bg=#ffffff,bold] #S #[fg=#f2f2f2,bg=#111111,nobold] #(whoami) #I:#P "
set -g status-right "#[fg=#f2f2f2,bg=#111111]%H:%M:%S | %d-%b-%y | #{?HOST_NICKNAME,#{HOST_NICKNAME},#H} "

setw -g window-status-format " #I:#W "
setw -g window-status-current-format "#[fg=#000000,bg=#7caff8,bold] #I:#W #[fg=#f2f2f2,bg=#111111,nobold]"
setw -g window-status-activity-style "fg=#7caff8,bg=#111111"

set -g pane-border-style "fg=#29292a"
set -g pane-active-border-style "fg=#7caff8"

set -g message-style "fg=#000000,bg=#7caff8"
set -g mode-style "fg=#000000,bg=#7caff8"

setw -g clock-mode-colour "#7caff8"
setw -g clock-mode-style 24
