source-file "${HOME}/.tmux/themes/llama.conf"

# Use ctrl-a as command prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Use ctrl-a + t to create a new session
unbind t
bind t new

# Use ctrl-a + tab and to switch between windows
bind -r Tab next-window
bind -r BTab previous-window

# Use ctrl-tab and ctrl-shift-tab (no prefix) to switch between windows
bind -n C-Tab next-window
bind -n C-BTab previous-window

# Use ctrl-a + shift-left/right to switch between windows
bind -r S-Right next-window
bind -r S-Left previous-window

# Use ctrl-<num> (no prefix) to jump between windows
bind -n C-1 select-window -t 1
bind -n C-2 select-window -t 2
bind -n C-3 select-window -t 3
bind -n C-4 select-window -t 4
bind -n C-5 select-window -t 5
bind -n C-6 select-window -t 6
bind -n C-7 select-window -t 7
bind -n C-8 select-window -t 8
bind -n C-9 select-window -t 9
bind -n C-0 last-window

# Number windows and panes from one instead of zero
set -g base-index 1
setw -g pane-base-index 1

# Use ctrl-a + - to split horizontal
bind - split-window -v
bind _ split-window -v

# Use ctrl-a + | to split veritcal
bind \\ split-window -h
bind | split-window -h

# Use ctrl-a + enter to zoom
bind Enter resize-pane -Z

# Use ctrl-a + r to reload config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded"

# Use ctrl-k (no prefix) to clear the screen and scrollback
bind -n C-k send-keys -R \; send-keys C-l \; clear-history

# Use vi mode
setw -g mode-keys vi

# Enable mouse input
set -g mouse on

# Increase scrollback
set-option -g history-limit 10000

# Allow apps to pass escape sequences through tmux (e.g. image protocols)
set -g allow-passthrough on

# Make sure dotfiles env var is not set
set-environment -g -r DOTFILES_BASH_INIT
