[language-server.emmet-language-server]
command = "emmet-language-server"
args = ["--stdio"]

[language-server.tailwindcss-language-server]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.pylsp.config]
# Tweak pycodestyle’s max-line-length to match black’s default line-length.
# This will need tweaking per-project in $project_root/.helix/language.toml
pylsp.plugins.pycodestyle.maxLineLength = 88

[language-server.vscode-eslint-language-server.config]
experimental.useFlatConfig = false
nodePath = ""
problems.shortenToSingleLine = false
rulesCustomizations = []
run = "onType"
validate = "on"

[language-server.vscode-html-language-server.config]
format.contentUnformatted = "code,css,pre,script,svg,textarea"
format.extraLiners = ""
format.indentInnerHtml = true
format.wrapAttributes = "preserve"
provideFormatter = true

[[language]]
name = "htmldjango"
block-comment-tokens = [
  { start = "{#", end = "#}" },
  { start = "{% comment %}", end = "{% endcomment %}" },
]
file-types = [
  { glob = "templates/**/*.html" },
]
formatter = { command = "djlint", args = ["-", "--quiet", "--reformat"] }
language-servers = [
  "djlsp",
  "vscode-html-language-server",
  "superhtml",
  "emmet-language-server",
  # "tailwindcss-language-server",  # enable per-project
]

[[language]]
name = "javascript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "jsx"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "html"
auto-format = true
language-servers = [
  "vscode-html-language-server",
  "superhtml",
  "emmet-language-server",
  # "tailwindcss-language-server",  # enable per-project
]

[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "tsx"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "python"
auto-format = true
